name: golang-pr

on:
  pull_request:

jobs:
  golang:
    permissions:
      contents: read
      pull-requests: write
      checks: write
    uses: depado/github-actions/.github/workflows/golang.yml@main
    with:
      skip-build: true
