name: golang

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 10
      - uses: gwatts/go-coverage-action@v2
        id: coverage
        with:
          fail-coverage: never
          cover-pkg: ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=3m
